// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfSnmRSsEAvcCdhpcNnE7LMJ92lO5dCaI',
    appId: '1:634856163331:web:4ebfd15f13c119d4d8e636',
    messagingSenderId: '634856163331',
    projectId: 'my-bees-40070',
    authDomain: 'my-bees-40070.firebaseapp.com',
    databaseURL: 'https://my-bees-40070-default-rtdb.firebaseio.com',
    storageBucket: 'my-bees-40070.appspot.com',
    measurementId: 'G-M26BC9MHKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWhurUfprXfY6syOBWtbElWK5GN8TGqK0',
    appId: '1:634856163331:android:c196b61f48bb4bf7d8e636',
    messagingSenderId: '634856163331',
    projectId: 'my-bees-40070',
    databaseURL: 'https://my-bees-40070-default-rtdb.firebaseio.com',
    storageBucket: 'my-bees-40070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJzRKt3kQhqnzP77n3s3nGDK_5Gzvt-jM',
    appId: '1:634856163331:ios:2b0d982d319c4f2fd8e636',
    messagingSenderId: '634856163331',
    projectId: 'my-bees-40070',
    databaseURL: 'https://my-bees-40070-default-rtdb.firebaseio.com',
    storageBucket: 'my-bees-40070.appspot.com',
    androidClientId: '634856163331-9rggu42dl8cuqsvt3hoff9kbos2hgjno.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJzRKt3kQhqnzP77n3s3nGDK_5Gzvt-jM',
    appId: '1:634856163331:ios:b91a36b770faef31d8e636',
    messagingSenderId: '634856163331',
    projectId: 'my-bees-40070',
    databaseURL: 'https://my-bees-40070-default-rtdb.firebaseio.com',
    storageBucket: 'my-bees-40070.appspot.com',
    androidClientId: '634856163331-9rggu42dl8cuqsvt3hoff9kbos2hgjno.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
